config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
    }

  root 'home#index'

  resources :posts do
    resources :comments, only: :create
  end

  get '*path' => redirect('/')

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text
#  user_id    :integer
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  default_scope { order(created_at: :desc) }

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    if @comment = @post.comments.create(comment_params)
      redirect_to post_path(@post), notice: 'Commentário cadastrado com sucesso.'
    else
      redirect_to post_path(@post), notice: 'Não foi possível inserir o seu comentário. Verifique se o mesmo está em branco.'
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.slim
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :content
    = f.association :user
    = f.association :post

  .form-actions
    = f.button :submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th Content
      th User
      th Post
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.content
        td = comment.user
        td = comment.post
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong Content:
  = @comment.content
p
  strong User:
  = @comment.user
p
  strong Post:
  = @comment.post

= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path