config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
    }

  root 'home#index'

  resources :posts do
    resources :comments, only: :create
  end

  get '*path' => redirect('/')

end

app/views/layouts/_dimmer_loading.html.slim
.ui.inverted.dimmer
  .ui.text.loader Processando sua requisição...

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
head
  title Blog RoR
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
body
  / Barra de navegação
  nav.ui.inverted.blue.pointing.menu.fixed.top
    = link_to content_tag(:i, '', class: 'tasks icon') << 'Blog RoR - Principais notícias sobre Ruby on Rails', root_path, class: "item", id: 'navbar-title', active: :exclusive
    .right.menu
      - if user_signed_in?
        = link_to content_tag(:i, '', class: 'edit icon') << "Nova Postagem", new_post_path, class: "item", id: 'navbar-title'
        = link_to content_tag(:i, '', class: 'newspaper icon') << "Postagens", posts_path, class: "item", id: 'navbar-title'
        .ui.simple.dropdown.item#navbar-title
          | #{content_tag(:i, '', class: 'user icon') << current_user.full_name.split(" ")[0].titleize}
          i.dropdown.icon
          .menu
            = link_to content_tag(:i, '', class: 'edit icon') << "Editar Meus Dados", edit_user_registration_path, class: 'item'
            .divider
            = link_to content_tag(:i, '', class: 'sign out icon') << "Sair", destroy_user_session_path, method: :delete, data: { confirm: 'Deseja sair do sistema?'}, class: 'item'
      - else
        = link_to content_tag(:i, '', class: 'edit icon') << "Registrar-se", new_user_registration_path, class: "item", id: 'navbar-title'
        = link_to content_tag(:i, '', class: 'newspaper icon') << "Acessar", new_user_session_path, class: "item", id: 'navbar-title'


  / Sessão de conteúdo da página.
  section
    #container
      = yield

  / Sessão do rodapé da página.
  footer
    p.text-center Copyright &copy; 2015 - Blog RoR - Todos os direitos reservados.